-- TrueShift schema v2 — DB as source of truth + lessons + cron infra.
-- Idempotent; safe to re-run.

-- ── Profiles: add app-data + preference columns ──────────────────────────────
alter table public.profiles
  add column if not exists onboarding_complete boolean not null default false,
  add column if not exists reminder_enabled    boolean not null default false,
  add column if not exists reminder_hour        int    not null default 20,
  add column if not exists reminder_minute      int    not null default 0,
  add column if not exists expo_push_token      text,
  add column if not exists push_last_sent_on    date,
  add column if not exists theme                text   not null default 'calmDark',
  add column if not exists text_size            text   not null default 'Normal',
  add column if not exists reduce_motion        boolean not null default false,
  add column if not exists read_aloud           boolean not null default false,
  add column if not exists lessons_watched      text[]  not null default '{}';

-- ── Lessons: shared content, seeded + AI-generated by cron ───────────────────
create table if not exists public.lessons (
  id             text primary key,           -- slug
  title          text not null,
  category       text not null,
  summary        text,
  action_preview text,
  intro          text,
  sections       jsonb not null default '[]'::jsonb,  -- [{heading, body}]
  actions        text[] not null default '{}',
  key_idea       text,
  voice_script   text,
  gradient       text[] not null default '{}',        -- [from, to]
  duration_label text default '4 min',
  source         text not null default 'ai',          -- 'seed' | 'ai'
  start_here     boolean not null default false,
  published      boolean not null default true,
  created_at     timestamptz not null default now()
);
create index if not exists lessons_published_created_idx on public.lessons (published, created_at desc);

alter table public.lessons enable row level security;
-- any signed-in user can read published lessons; writes happen only via the
-- service key (edge functions/cron), which bypasses RLS.
drop policy if exists "lessons_select_published" on public.lessons;
create policy "lessons_select_published" on public.lessons
  for select using (auth.role() = 'authenticated' and published = true);

-- ── Extensions for scheduled jobs + outbound HTTP from Postgres ──────────────
create extension if not exists pg_cron;
create extension if not exists pg_net;
