import React, { useEffect, useState, useCallback } from 'react';
import { View, Pressable, TextInput, ActivityIndicator } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Screen, Card } from '../../components/Screen';
import { AppText } from '../../components/AppText';
import { Button } from '../../components/Button';
import { FlowHeader } from '../../components/Header';
import { Icon } from '../../components/icons';
import { useTheme } from '../../theme/ThemeContext';
import { useApp } from '../../store/AppState';
import { useResetFlow } from '../../store/ResetFlow';
import { useRootNav } from '../../navigation/hooks';
import { situationById } from '../../data/situations';
import { aiEnabled } from '../../ai/config';
import { generateReset } from '../../ai/openai';
import { radius, spacing } from '../../theme/tokens';

/**
 * Step 2 — AI-personalised support (with a safe static fallback).
 *   validate (first) → editable reframe ("another way to see it") → one step.
 * Content is generated by the CBT brain, non-repeating vs the user's history,
 * and gated by crisis + moderation checks. If AI is off/fails, falls back to the
 * vetted-draft copy in situations.ts so the flow never dead-ends.
 */
export function SupportScreen() {
  const { theme, tint, scale } = useTheme();
  const { resets } = useApp();
  const { draft, update } = useResetFlow();
  const nav = useRootNav();
  const c = theme.colors;

  const situation = situationById(draft.situationId ?? 'somethingElse')!;
  const label = draft.situationLabel || situation.label;

  const [loading, setLoading] = useState(aiEnabled);
  const [validate, setValidate] = useState(situation.validate);
  const [reframe, setReframe] = useState(situation.reframe);
  const [step, setStep] = useState(situation.actions[0].text);
  const [narration, setNarration] = useState('');
  const [keywords, setKeywords] = useState<string[]>([]);
  const [distortion, setDistortion] = useState('');
  const [source, setSource] = useState<'ai' | 'fallback'>('fallback');
  const [editing, setEditing] = useState(false);
  const [note, setNote] = useState(draft.note ?? '');
  const [showNote, setShowNote] = useState(false);
  const [altIdx, setAltIdx] = useState(0);

  const recentReframes = resets.map((r) => r.reframe).filter(Boolean) as string[];
  const recentSteps = resets.map((r) => r.actionText).filter(Boolean) as string[];

  const applyFallback = useCallback(() => {
    setSource('fallback');
    setValidate(situation.validate);
    setReframe(situation.reframe);
    setStep(situation.actions[0].text);
    setNarration(`${situation.validate} ${situation.reframe} A small step: ${situation.actions[0].text}`);
    setKeywords([]);
    setDistortion('');
  }, [situation]);

  const runAI = useCallback(
    async (avoidR: string[], avoidS: string[]) => {
      setLoading(true);
      try {
        const r = await generateReset({
          situationLabel: label,
          customSituation: draft.customSituation,
          heaviness: draft.heaviness,
          note: note || draft.note,
          avoidReframes: avoidR,
          avoidSteps: avoidS,
        });
        if (r.crisis) {
          nav.navigate('CrisisResources');
          return;
        }
        setSource('ai');
        setValidate(r.validate || situation.validate);
        setReframe(r.reframe || situation.reframe);
        setStep(r.smallStep || situation.actions[0].text);
        setNarration(r.narration || `${r.validate} ${r.reframe} A small step: ${r.smallStep}`);
        setKeywords(r.keywords || []);
        setDistortion(r.distortion || '');
      } catch {
        applyFallback();
      } finally {
        setLoading(false);
      }
    },
    [label, draft.customSituation, draft.heaviness, draft.note, note, nav, situation, applyFallback]
  );

  useEffect(() => {
    if (aiEnabled) runAI(recentReframes.slice(0, 6), recentSteps.slice(0, 6));
    else applyFallback();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const differentStep = () => {
    if (source === 'ai') {
      runAI([reframe, ...recentReframes].slice(0, 6), [step, ...recentSteps].slice(0, 6));
    } else {
      const i = (altIdx + 1) % situation.actions.length;
      setAltIdx(i);
      setStep(situation.actions[i].text);
    }
  };

  const next = () => {
    update({ situationLabel: label, reframe, actionText: step, narration, keywords, distortion, note: note || undefined, aiGenerated: source === 'ai' });
    nav.navigate('ResetNarration');
  };

  if (loading) return <ThinkingState />;

  return (
    <Screen scroll glow="teal" bottom={<Button label="Hear my reset" large icon="speaker" onPress={next} />}>
      <FlowHeader progress={0.6} onBack={() => nav.goBack()} readAloudText={`${validate} ${reframe} A small step: ${step}`} />

      <AppText size={20} weight="700" lineHeightMultiple={1.35}>{validate}</AppText>

      <View style={{ marginTop: spacing.xl, borderRadius: radius.xxl, borderWidth: c.borderWidth, borderColor: tint(c.teal, 0.3), backgroundColor: c.card, overflow: 'hidden' }}>
        <LinearGradient colors={[tint(c.teal, 0.14), tint(c.lavender, 0.1)]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }} />
        <View style={{ padding: spacing.xl }}>
          <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.md }}>
            <AppText size={12} weight="700" color={c.teal} uppercase letterSpacing={0.8}>Another way to see it</AppText>
            {source === 'ai' && <AppText size={11} color={c.muted}>personalised</AppText>}
          </View>
          {editing ? (
            <TextInput value={reframe} onChangeText={setReframe} multiline autoFocus allowFontScaling style={{ color: c.text1, fontSize: scale(17), lineHeight: scale(25), minHeight: scale(80), textAlignVertical: 'top' }} />
          ) : (
            <AppText size={17} lineHeightMultiple={1.45}>{reframe}</AppText>
          )}
        </View>
      </View>
      <Pressable onPress={() => setEditing((e) => !e)} accessibilityRole="button" accessibilityLabel={editing ? 'Done editing' : 'Put it in my own words'} style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, marginTop: spacing.md, minHeight: 44 }}>
        <Icon name="edit" color={c.text2} size={16} />
        <AppText size={14} color={c.text2}>{editing ? 'Done' : 'Put it in my own words'}</AppText>
      </Pressable>

      {showNote ? (
        <Card style={{ marginTop: spacing.sm }}>
          <AppText size={12} weight="600" color={c.muted}>The thought underneath (optional)</AppText>
          <TextInput value={note} onChangeText={setNote} placeholder="What did your mind say?" placeholderTextColor={c.muted} multiline allowFontScaling style={{ color: c.text1, fontSize: scale(15), marginTop: spacing.sm, minHeight: scale(40), textAlignVertical: 'top' }} />
        </Card>
      ) : (
        <Pressable onPress={() => setShowNote(true)} accessibilityRole="button" accessibilityLabel="Add the thought underneath" style={{ alignItems: 'center', minHeight: 36, justifyContent: 'center' }}>
          <AppText size={13} color={c.muted}>+ Add the thought underneath</AppText>
        </Pressable>
      )}

      <AppText size={12} weight="700" color={c.muted} uppercase letterSpacing={0.8} style={{ marginTop: spacing.xl }}>One small step</AppText>
      <Card intent="accent" style={{ marginTop: spacing.md, borderColor: tint(c.teal, 0.3) }}>
        <AppText size={17} weight="600" lineHeightMultiple={1.35}>{step}</AppText>
        <Pressable onPress={differentStep} accessibilityRole="button" accessibilityLabel="Try a different step" style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.md, minHeight: 36 }}>
          <Icon name="shift" color={c.text2} size={16} />
          <AppText size={13} color={c.text2}>Try a different step</AppText>
        </Pressable>
      </Card>
    </Screen>
  );
}

function ThinkingState() {
  const { theme, tint, reduceMotion } = useTheme();
  const c = theme.colors;
  return (
    <Screen center glow="teal">
      <View style={{ alignItems: 'center', gap: spacing.xl }}>
        <View style={{ width: 96, height: 96, borderRadius: radius.full, borderWidth: 1.5, borderColor: tint(c.teal, 0.4), alignItems: 'center', justifyContent: 'center' }}>
          <ActivityIndicator color={c.teal} />
        </View>
        <AppText size={18} weight="600" color={c.text2}>Thinking with care…</AppText>
      </View>
    </Screen>
  );
}
