import { OPENAI_API_KEY, OPENAI_MODEL, SYSTEM_PROMPT, AI_TIMEOUT_MS, aiEnabled } from './config';
import { localCrisisCheck, moderationFlagged } from './safety';

/** Structured result for one reset, generated by the CBT "brain". */
export interface AIReset {
  crisis: boolean;
  validate: string;
  reframe: string;
  smallStep: string;
  narration: string; // short spoken script for the voice
  keywords: string[]; // 2–4 thought/keyword tags for the Insights map
  distortion: string; // a plain-language thinking pattern name, or ''
}

interface GenerateInput {
  situationLabel: string;
  customSituation?: string;
  heaviness?: number;
  emotion?: string;
  note?: string;
  avoidReframes?: string[];
  avoidSteps?: string[];
  avoidValidations?: string[];
}

async function chatJSON(userContent: string, temperature = 0.8): Promise<any> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), AI_TIMEOUT_MS);
  let res: Response;
  try {
    res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      signal: ctrl.signal,
      headers: { Authorization: `Bearer ${OPENAI_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: OPENAI_MODEL,
        temperature,
        max_tokens: 750,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userContent },
        ],
      }),
    });
  } finally {
    clearTimeout(timer);
  }
  if (!res.ok) throw new Error(`OpenAI ${res.status}`);
  const json = await res.json();
  const content = json?.choices?.[0]?.message?.content;
  if (!content) throw new Error('OpenAI empty');
  return JSON.parse(content);
}

/**
 * Generate the personalised, non-repeating reset content. Runs crisis +
 * moderation gates first; returns crisis:true to route the user to support.
 */
export async function generateReset(input: GenerateInput): Promise<AIReset> {
  const userText = [input.customSituation, input.note].filter(Boolean).join(' ');

  if (localCrisisCheck(userText) || localCrisisCheck(input.situationLabel)) {
    return crisisResult();
  }
  if (userText && (await moderationFlagged(userText))) {
    return crisisResult();
  }

  const prompt = [
    `Situation the user picked: "${input.situationLabel}".`,
    input.customSituation ? `In their words: "${input.customSituation}".` : '',
    input.emotion ? `They named the feeling as: "${input.emotion}". Acknowledge this emotion by name in the validation.` : '',
    input.note ? `The thought underneath: "${input.note}".` : '',
    input.heaviness ? `They rated how heavy it feels: ${input.heaviness} of 5.` : '',
    input.avoidReframes?.length ? `Do NOT reuse or paraphrase these earlier reframes: ${JSON.stringify(input.avoidReframes)}.` : '',
    input.avoidSteps?.length ? `Do NOT reuse or paraphrase these earlier steps: ${JSON.stringify(input.avoidSteps)}.` : '',
    input.avoidValidations?.length ? `Do NOT reuse or paraphrase these earlier validations: ${JSON.stringify(input.avoidValidations)}.` : '',
    `WRITING RULES:`,
    `- "validate" must be SPECIFIC to this exact situation and varied. NEVER use formulaic openers like "It's normal", "It makes sense", "It's okay", "Many people", "A lot of people", "That's understandable". Reflect back the specific tension in their words instead.`,
    `- "reframe" is a fuller cognitive restructuring — 3 to 4 sentences: (1) name the thinking trap gently, (2) offer the balanced alternative thought, (3) give a brief reason it holds up (evidence for/against, grounded in THEIR situation). Do NOT begin with "Another way", "Maybe", "Perhaps", or "Try to". Warm, plain, concrete.`,
    `- "smallStep": vary the TYPE of step across CBT techniques — behavioural experiment, opposite action, urge-surf/delay, values-based action, grounding, self-compassion, reaching out, or problem-solving — pick the one that best fits this situation. Always concrete, with a when/where and a tiny time.`,
    `- Vary phrasing each time; do not sound templated.`,
    `Return minified JSON with exactly these keys:`,
    `{"crisis":false,`,
    `"validate":"one specific, warm validating sentence, no clichés (<=140 chars)",`,
    `"reframe":"3-4 sentence balanced cognitive reframe with a brief supporting reason, no boilerplate prefix (<=520 chars)",`,
    `"smallStep":"one concrete action (varied CBT technique) with a when/where and a tiny time (<=140 chars)",`,
    `"narration":"a calm 3-5 sentence spoken script weaving the validation, the reframe, and the step naturally (<=520 chars)",`,
    `"keywords":["2-4 short lowercase thought tags, e.g. 'mind-reading','self-criticism'"],`,
    `"distortion":"one plain-language thinking pattern name, or empty string"}`,
  ]
    .filter(Boolean)
    .join('\n');

  const data = await chatJSON(prompt);
  const out: AIReset = {
    crisis: Boolean(data.crisis),
    validate: String(data.validate ?? ''),
    reframe: String(data.reframe ?? ''),
    smallStep: String(data.smallStep ?? ''),
    narration: String(data.narration ?? ''),
    keywords: Array.isArray(data.keywords) ? data.keywords.slice(0, 4).map((k: any) => String(k)) : [],
    distortion: String(data.distortion ?? ''),
  };
  // Final output moderation — if the model produced something flagged, fail safe.
  if (out.reframe && (await moderationFlagged(`${out.reframe} ${out.smallStep} ${out.narration}`))) {
    return crisisResult();
  }
  return out;
}

/** Personalised extra situation chips, appended to the base list. Never throws fatally. */
export async function suggestSituations(recentSituations: string[], baseLabels: string[]): Promise<string[]> {
  try {
    const prompt = [
      `The user's recent situations were: ${JSON.stringify(recentSituations.slice(0, 8))}.`,
      `The fixed base options already shown are: ${JSON.stringify(baseLabels)}.`,
      `Suggest up to 3 ADDITIONAL concrete, everyday situation labels this user is likely to face, that are NOT duplicates of the base options.`,
      `Each label: first-person feel, <= 30 chars, plain words, no diagnosis.`,
      `Return minified JSON: {"situations":["...","..."]}`,
    ].join('\n');
    const data = await chatJSON(prompt, 0.6);
    const arr = Array.isArray(data.situations) ? data.situations : [];
    return arr.map((s: any) => String(s)).filter((s: string) => s && s.length <= 40).slice(0, 3);
  } catch {
    return [];
  }
}

function crisisResult(): AIReset {
  return { crisis: true, validate: '', reframe: '', smallStep: '', narration: '', keywords: [], distortion: '' };
}

/** One scheduled reminder — a gentle, personalised daily nudge. */
export interface ReminderMessage {
  title: string;
  body: string;
}

export interface ReminderHistory {
  /** most-recent-first recent situation labels the user actually faced */
  recentSituations: string[];
  /** most-recent-first recent emotions they named */
  recentEmotions: string[];
  /** the single most common situation label, if any */
  topSituation?: string | null;
  /** their last reset's small step + whether they marked it done */
  lastActionText?: string | null;
  lastActionDone?: boolean | null;
  /** current streak of days with a reset */
  streak?: number;
  /** total resets ever (0 = brand new user) */
  total?: number;
  /** first name to optionally use, or 'there' */
  name?: string;
}

/**
 * Generate `count` DISTINCT daily reminder messages, personalised to the user's
 * own history. These are pre-generated and scheduled locally (notifications
 * can't run code at fire time). Rotates intent across days: check-in, follow-up
 * on their last step, pattern reflection, gentle encouragement.
 *
 * Always safe: templated fallback if AI is unavailable, and every message is
 * moderation-checked as a batch before being returned.
 */
export async function generateReminders(history: ReminderHistory, count: number): Promise<ReminderMessage[]> {
  const n = Math.max(1, Math.min(count, 7));
  if (!aiEnabled) return fallbackReminders(history, n);
  try {
    const brandNew = !history.total || history.total === 0;
    const prompt = [
      `Write ${n} short, warm push-notification reminders for a CBT self-help app called TrueShift, one per day for the next ${n} days.`,
      `Each nudges the user to take a 2-minute "reset" (name what's on their mind → one balanced thought → one small step).`,
      brandNew
        ? `This user is brand new — no history yet. Keep it welcoming and low-pressure; invite them to try their first reset.`
        : [
            `Personalise using THIS user's real history (do not invent facts beyond it):`,
            history.recentSituations?.length ? `- Recent situations they faced: ${JSON.stringify(history.recentSituations.slice(0, 6))}.` : '',
            history.recentEmotions?.length ? `- Recent feelings they named: ${JSON.stringify(history.recentEmotions.slice(0, 6))}.` : '',
            history.topSituation ? `- Their most common theme: "${history.topSituation}".` : '',
            history.lastActionText ? `- Their last small step was: "${history.lastActionText}" (${history.lastActionDone ? 'they marked it done' : 'not yet done'}).` : '',
            typeof history.streak === 'number' ? `- Current streak: ${history.streak} day(s).` : '',
          ]
            .filter(Boolean)
            .join('\n'),
      `ROTATE the intent across the ${n} days so they don't feel repetitive — mix of: a gentle check-in ("how are you feeling about X today?"), a follow-up on their last step, a reflection on a pattern you can see, and light encouragement. Do NOT repeat the same angle twice.`,
      `RULES:`,
      `- Non-annoying, never nagging, never guilt-inducing. No streak pressure, no "don't break your streak".`,
      `- Warm, calm, adult, plain language. No emojis. No clinical jargon. Not therapy.`,
      `- Reference their history naturally when useful, but never quote sensitive text verbatim or sound surveillant.`,
      `- title <= 40 chars, body <= 110 chars. Each message DISTINCT.`,
      history.name && history.name !== 'there' ? `- You may occasionally use their name "${history.name}", but sparingly.` : '',
      `Return minified JSON: {"reminders":[{"title":"...","body":"..."}, ...]} with exactly ${n} items.`,
    ]
      .filter(Boolean)
      .join('\n');

    const data = await chatJSON(prompt, 0.9);
    let arr: ReminderMessage[] = Array.isArray(data.reminders)
      ? data.reminders
          .map((r: any) => ({ title: String(r?.title ?? '').slice(0, 60), body: String(r?.body ?? '').slice(0, 160) }))
          .filter((r: ReminderMessage) => r.title && r.body)
      : [];
    if (!arr.length) return fallbackReminders(history, n);

    // Batch output moderation — if anything is flagged, fall back to safe copy.
    if (await moderationFlagged(arr.map((r) => `${r.title} ${r.body}`).join('\n'))) {
      return fallbackReminders(history, n);
    }
    return arr.slice(0, n);
  } catch {
    return fallbackReminders(history, n);
  }
}

/** Safe, still-lightly-personalised reminders when AI is unavailable. */
export function fallbackReminders(history: ReminderHistory, count: number): ReminderMessage[] {
  const name = history.name && history.name !== 'there' ? history.name : '';
  const hi = name ? `${name}, ` : '';
  const theme = history.topSituation || (history.recentSituations && history.recentSituations[0]);
  const pool: ReminderMessage[] = [
    { title: 'A quiet minute for you', body: `${hi}whatever today held, two minutes can help it feel lighter.`.trim() },
    { title: 'How are you, really?', body: 'Name what’s on your mind and take one small step. That’s all it takes.' },
    theme
      ? { title: 'One small reset', body: `If “${theme}” is on your mind again, a quick reset can steady it.`.slice(0, 130) }
      : { title: 'One small reset', body: 'A steadier mind is one thought and one small step away.' },
    history.lastActionText
      ? { title: 'Following up', body: 'Did your last small step happen? Either way, today is a fresh start.' }
      : { title: 'Two minutes, that’s it', body: 'Check in with yourself — one balanced thought can shift the day.' },
    { title: 'Still here for you', body: 'When something feels heavy, open TrueShift and take one small step.' },
    { title: 'A gentle check-in', body: `${hi}how are you feeling right now? A short reset is ready when you are.`.trim() },
    { title: 'Your daily reset', body: 'One honest thought, one small step. Let’s take a calm minute together.' },
  ];
  const out: ReminderMessage[] = [];
  for (let i = 0; i < count; i++) out.push(pool[i % pool.length]);
  return out.map((r) => ({ title: r.title.slice(0, 60), body: r.body.slice(0, 160) }));
}
